version: '3.4'

services:
  lab2:
    image: ${DOCKER_REGISTRY-}lab2
    build:
      context: .
      dockerfile: Lab2/Dockerfile 
    ports:
      - "8080:8080"
  db:
    image: postgres:14
    hostname: postgres.local
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "123"
      POSTGRES_DB: "lab_db"
    ports:
      - "5432:5432"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - pg-data:/var/lib/postgresql/data
      - pg-conf:/etc/postgresql
      - pg-log:/var/log/postgresql
    restart: always

volumes:
  pg-data: {}
  pg-conf: {}
  pg-log: {}
